config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
  end
  devise_for :professors
  get 'site/welcome/index'
  resources :grades
  root to: "site/welcome#index"
  get "home", to: "site/welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grade.rb
class Grade < ApplicationRecord
end

app/models/professor.rb
class Professor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base    
    before_action :set_locale

    def set_locale
        if params[:locale] 
            cookies[:locale] = params[:locale]
        end

        if cookies[:locale]
            if I18n.locale != cookies[:locale]
                I18n.locale = cookies[:locale]
            end
        end
    end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :authenticate_professor!
  before_action :set_grade, only: [:show, :edit, :update, :destroy]
  

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:name, :average, :bim1, :bim2, :bim3, :bim4)
    end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/helpers/application_helper.rb
module ApplicationHelper
    def time_helper()
        date = Time.new
        date.strftime("%H:%M")
    end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/grades/_form.html.erb
<%= form_with(model: grade, local: true) do |form| %>
  <% if grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="form-group">
      <div class="field">
        <%= form.label t('edit.name') %>
        <%= form.text_field :name, class:"form-control", placeholder:t('new.name'), :required => true%>
      </div>
    </div>
    
    <div class="form-group">
      <div class="field">
        <%= form.label :bim1 %>
        <%= form.number_field :bim1, min: 0, step:0.5, max: 10, class:"form-control", placeholder:t('new.first_grade'), :required => true %>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= form.label :bim2 %>
        <%= form.number_field :bim2, min: 0, step:0.5,max: 10, class:"form-control", placeholder:t('new.second_grade'), :required => true %>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= form.label :bim3 %>
        <%= form.number_field :bim3, min: 0, step:0.5,max: 10, class:"form-control", placeholder:t('new.third_grade'), :required => true %>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= form.label :bim4 %>
        <%= form.number_field :bim4, min: 0, step:0.5,max: 10, class:"form-control", placeholder:t('new.fourth_grade'), :required => true %>
      </div>
    </div>
    <div class="actions">
      <%= form.submit nil, class:"btn btn-primary" %>
    </div>
  </form>
<% end %>
<br>

app/views/grades/edit.html.erb
<br>
<h1><%= t('edit.edith1') %></h1>

<%= render 'form', grade: @grade %>

<%= link_to t('edit.show'), @grade, class:"btn btn-primary" %> |
<%= link_to t('edit.back'), grades_path, class:"btn btn-primary" %>

app/views/grades/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('grades.grades') %></h1>

<table class="table table-hover table-bordered">
  <thead class="thead-light">
    <tr>
      <th>Id</th>
      <th><%= t('grades.table.name') %></th>
      <th><%= t('grades.table.average') %></th>
      <th>Bim1</th>
      <th>Bim2</th>
      <th>Bim3</th>
      <th>Bim4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= grade.id %></td>
        <td><%= grade.name %></td>
        <td><%= grade.average %></td>
        <td><%= grade.bim1 %></td>
        <td><%= grade.bim2 %></td>
        <td><%= grade.bim3 %></td>
        <td><%= grade.bim4 %></td>
        <td><%= link_to t('grades.show'), grade %></td>
        <td><%= link_to t('grades.edit'), edit_grade_path(grade) %></td>
        <td><%= link_to t('grades.destroy'), grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('grades.new'), new_grade_path, class:"btn btn-primary"  %>
<br><br><br><br>

app/views/grades/new.html.erb
<br>
<h1><%= t('new.newh1') %></h1>

<%= render 'form', grade: @grade %>

<%= link_to t('new.back'), grades_path, class:"btn btn-primary" %>

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('show.showh1') %></h1>

<form>
    <div class="form-group">
      <strong><%= t('show.name') %></strong>
      <%= text_field_tag nil, @grade.name, class:"form-control", disabled: true %>
    </div>
  <% @sum = 0.0%>

    <div class="form-group">
      <strong><%= t('show.average') %></strong>
      <% @sum = ((@grade.bim1 +  @grade.bim2 +  @grade.bim3 + @grade.bim4) /4).round(1) %>
      <%= text_field_tag nil, @sum, class:"form-control", disabled: true %>
    </div>

  <% @id = params[:id] %>
  <% if @sum != @grade.average %> 
    <% ActiveRecord::Base.connection.exec_query("UPDATE GRADES SET AVERAGE = #{@sum} WHERE id=#{@id}") %>
  <% end %>
  <!-- Apenas atualiza a media se o resultado do @sum for diferente da q esta no banco -->

  <div class="form-group">
    <strong>Bim1</strong>
    <%= text_field_tag nil, @grade.bim1, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <strong>Bim2</strong>
    <%= text_field_tag nil, @grade.bim2, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <strong>Bim3</strong>
    <%= text_field_tag nil, @grade.bim3, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <strong>Bim4</strong>
    <%= text_field_tag nil, @grade.bim4, class:"form-control", disabled: true %>
  </div>
</form>

<%= link_to t('show.edit'), edit_grade_path(@grade), class:"btn btn-primary" %> |
<%= link_to t('show.back'), grades_path, class:"btn btn-primary" %>
<br><br><br>

app/views/layouts/_content.html.erb
<br><br><br>
<!--<div class="card">
  <div class="card-header p-3 mb-2 bg-success text-white" >
    Featured
  </div>
  <div class="card-body ">
    <h5 class="card-title">New methods to teach</h5>
    <p class="card-text">5 New Teaching Methods Improving Education</p>
    <%= link_to 'Check out', "https://bit.ly/2GgUPdn", class:"btn btn-danger"%>
  </div>
</div>

<br><br><br>
<div class="card">
  <div class="card-header p-3 mb-2 bg-warning text-white" >
    Featured
  </div>
  <div class="card-body ">
    <h5 class="card-title">New methods to teach</h5>
    <p class="card-text">5 New Teaching Methods Improving Education</p>
    <%= link_to 'Check out', "https://bit.ly/2GgUPdn", class:"btn btn-danger"%>
  </div>
</div>

<br><br><br>
<div class="card">
  <div class="card-header p-3 mb-2 bg-danger text-white" >
    Featured
  </div>
  <div class="card-body ">
    <h5 class="card-title">New methods to teach</h5>
    <p class="card-text">5 New Teaching Methods Improving Education</p>
    <%= link_to 'Check out', "https://bit.ly/2GgUPdn", class:"btn btn-danger"%>
  </div>
</div>

<br><br><br>
<div class="card">
  <div class="card-header p-3 mb-2 bg-info text-white" >
    Featured
  </div>
  <div class="card-body ">
    <h5 class="card-title">New methods to teach</h5>
    <p class="card-text">5 New Teaching Methods Improving Education</p>
    <%= link_to 'Check out', "https://bit.ly/2GgUPdn", class:"btn btn-danger"%>
  </div>
</div>-->

<div class="card-deck">
  <div class="card">
    <%= image_tag 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Heiwa_elementary_school_18.jpg/350px-Heiwa_elementary_school_18.jpg'%>
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaJ2k9gR4sesy1mf-3ZcVhD52SfQCW5T91NBG-nOb2Pczimbnn'%>
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqktCpoz81dMFu2hzxyycPM1Bi8ctla2bt7BP5evaAIQCeSelhhQ'%>
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>
<br>

<br>
<div class="card">
  <div class="card-header p-3 mb-2 bg-success text-white" >
    Featured
  </div>
  <div class="card-body ">
    <h5 class="card-title">New methods to teach</h5>
    <p class="card-text">5 New Teaching Methods Improving Education</p>
    <%= link_to 'Open', "https://bit.ly/2GgUPdn", class:"btn btn-danger"%>
  </div>
</div>

<br>
<div class="card text-center">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

<br>
<div class="card-group">
  <div class="card">
    <img class="card-img-top" src="https://www.wonderplugin.com/videos/demo-image0.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://www.wonderplugin.com/videos/demo-image0.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://www.wonderplugin.com/videos/demo-image0.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-primary" style="padding: 0px 5px 0px 5px;">
    <nav class="navbar navbar-light">
    <div title="<%= t('navbar_MSG') %>">
        <%= link_to image_tag("https://bit.ly/2UQNtAG", size: "50x50") + t('navbar_MSG'), root_path, class:"navbar-brand" %>
    </div>
</nav>
<div>
<% if professor_signed_in? %>
    <%= link_to('Logout', destroy_professor_session_path, method: :delete, class:"btn btn-danger") %>
<% else %>
    <%= link_to('Login', new_professor_session_path, class:"btn btn btn-success") %>
<% end %>
</div>
<select id="language" class="custom-select" style="width:200px " onchange="location = this.value;">
    <option selected><%= t('select.choose') %></option>
    <option value="?locale=pt-BR"><%= t('select.portguese') %></option>
    <option value="?locale=en"><%= t('select.english') %></option>
</select>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('title') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <% @current = params[:controller] + "#" + params[:action]%>
    <% if @current != "devise/sessions#new" && @current != "devise/sessions#create"%>
      <% @login_page = true %>
      <%= render "layouts/navbar" %>
      <div class="container">
      <% else %>
        <% 2.times do |n| %>
          <br>
        <% end %>
    <% end %>
    <%= yield %>
      <% if @login_page %>
        <%= render "layouts/content" %>
      </div>
      <br>
      <p style="
                font-size: 130%;
                text-align: center;
                border-radius: 2px;
                padding: 10px;" class="p-3 mb-2 bg-info text-white">
                <strong>Hora atual: <%= time_helper() %></strong></p>
    </body>
    <% end %>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('title') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <% @current = params[:controller] + "#" + params[:action]%>
    <% if @current != "devise/sessions#new" && @current != "devise/sessions#create"%>
      <% @login_page = true %>
      <%= render "layouts/navbar" %>
      <div class="container">
      <% else %>
        <% 2.times do |n| %>
          <br>
        <% end %>
    <% end %>
    <%= yield %>
      <% if @login_page %>
        <%= render "layouts/content" %>
      </div>
      <br>
      <p style="
                font-size: 130%;
                text-align: center;
                border-radius: 2px;
                padding: 10px;" class="p-3 mb-2 bg-info text-white">
                <strong>Hora atual: <%= time_helper() %></strong></p>
    </body>
    <% end %>
</html>

app/views/professors/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class:"btn btn-primary" %><br />
<% end -%>
<br>
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class:"btn btn-primary" %>
  &nbsp;
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class:"btn btn-primary" %><br><br>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/site/welcome/index.html.erb
<br><br>
<div class="jumbotron">
    <h1 class="display-4"><%= t('welcome.welcome') %></h1>
    <p class="lead"><%= t('welcome.desc') %></p>
    <hr class="my-4">
    <p><%= t('welcome.start') %></p>
    <%= link_to t('welcome.check'), grades_path, class:"btn btn-primary btn-lg" %>
    <%= link_to t('welcome.submit'), new_grade_path, class:"btn btn-primary btn-lg" %>
</div>